server {
    listen 127.0.0.1:80 default_server;
    listen [::1]:80 default_server;

    server_name _;
    root /var/www/kiosk-app/public;
    index index.php index.html;

    access_log /var/log/nginx/doorscan-id-device-access.log;
    error_log /var/log/nginx/doorscan-id-device-error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
